GITHUB_OWNER = 'VLMedvedev'
GITHUB_REPOSITORY = 'mp_ota_from_git'
GITHUB_BRANCH = 'main'
GITHUB_APP_FOLDER = 'app'
GITHUB_TOKEN = ""
EXCLUDE_LIST = "sha1_internal_save_file.json"
AUTO_UPDATE_FROM_GIT = False
REBUILD_SHA1_INTERNAL_FILE = False
