APP_NAME = "Battery monitor"
APP_DOMAIN = "power-storage.eu"

AUTO_CONNECT_TO_WIFI_AP = True
AUTO_START_CAPTIVE_PORTAL = False
AUTO_SETUP_TIME = True
AUTO_START_WEBREPL = False
AUTO_START_WEBAPP = True
AUTO_START_SETUP_WIFI = False
AUTO_START_UMQTT = True
AUTO_RESTART_AFTER_UPDATE = False


